/**
 * The config the Bridge child is started with.
 *
 * CLIProxyAPI reads a YAML file and hot-reloads it, so this is generated on
 * every start rather than shipped as an asset: the port is scanned, the auth
 * directory is Foundry's own, and neither is knowable at build time.
 *
 * It is emitted by hand instead of through a YAML library. The key set is
 * fixed and small, the output has to be byte-stable so an unchanged config is
 * an unchanged file, and adding a YAML dependency to serialize eleven keys
 * would be a supply-chain cost with no matching benefit.
 */

export interface BridgeConfigInput {
  port: number;
  authDir: string;
  /** Verbose child logging. Off by default: the log is not the trace. */
  debug?: boolean;
}

/**
 * Values that are not options.
 *
 * `host` is pinned to 127.0.0.1 and `allow-remote` to false because the Bridge
 * holds the operator's provider subscriptions: a bind on 0.0.0.0 would put
 * their Claude and Codex accounts on the local network. `secret-key` empty
 * disables the management API entirely, which is the smallest surface that
 * still serves models.
 */
export const BRIDGE_HOST = '127.0.0.1';

export function renderBridgeConfig(input: BridgeConfigInput): string {
  const lines = [
    '# Generated by Foundry. Edits are overwritten on the next Bridge start.',
    `port: ${input.port}`,
    `host: "${BRIDGE_HOST}"`,
    `auth-dir: ${quote(input.authDir)}`,
    'remote-management:',
    '  allow-remote: false',
    '  secret-key: ""',
    '  disable-control-panel: true',
    `debug: ${input.debug ? 'true' : 'false'}`,
    'logging-to-file: false',
    'usage-statistics-enabled: false',
    'api-keys: []',
    'proxy-url: ""',
    'request-retry: 3',
    // 0 removes the cap, so one request sweeps every authenticated account for
    // a provider before an error reaches pi. Multi-account failover then costs
    // the agent nothing: it never sees the first account's quota error.
    'max-retry-credentials: 0',
    // Extended thinking turns routinely exceed the 10m default on a long phase.
    'request-timeout: "30m"',
    'routing:',
    '  strategy: "round-robin"',
    // Responses API traffic carries encrypted reasoning state keyed to the
    // account that produced it, so a follow-up turn landing on a different
    // account breaks the session rather than merely costing a cache miss.
    '  session-affinity: true',
    '  session-affinity-ttl: "2h"',
    'quota-exceeded:',
    '  switch-project: true',
    '  switch-preview-model: true',
    '',
  ];
  return lines.join('\n');
}

/** YAML double-quoting for a filesystem path, which may contain spaces. */
function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
